### ISSUE TITLE
 Task 2.1.2: Implement Zcash RPC functionality required by lightwallet services.

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#111]
Implement Zcash RPC functionality required by lightwallet services. 
This should be implemented as methods on `StateService` with identical functionality to the following Zcash RPCs:
- [x] [[getinfo](https://zcash.github.io/rpc/getinfo.html)]
- [x] [[getblockchaininfo](https://zcash.github.io/rpc/getblockchaininfo.html)]
- [x] [[getaddressbalance](https://zcash.github.io/rpc/getaddressbalance.html)]
- [x] [[send_raw_transaction](https://zcash.github.io/rpc/sendrawtransaction.html)]
- [x] [[getblock](https://zcash.github.io/rpc/getblock.html)]
- [x] [[getrawmempool](https://zcash.github.io/rpc/getrawmempool.html)]
- [x] [[z_gettreestate](https://zcash.github.io/rpc/z_gettreestate.html)]
- [x] [[z_getsubtreesbyindex](https://zcash.github.io/rpc/z_getsubtreesbyindex.html)]
- [x] [[get_raw_transaction](https://zcash.github.io/rpc/getrawtransaction.html)]
- [x] [[getaddresstxids](https://zcash.github.io/rpc/getaddresstxids.html)]
- [x] [[getaddressutxos](https://zcash.github.io/rpc/getaddressutxos.html)]

The following RPCs will be completed in #59:
- [getaddressdeltas](https://zcash.github.io/rpc/getaddressdeltas.html)
- [getaddressutxos](https://zcash.github.io/rpc/getaddressutxos.html)
- [getblockcount](https://zcash.github.io/rpc/getblockcount.html)
- [getblockdeltas](https://zcash.github.io/rpc/getblockdeltas.html)
- [getblockhash](https://zcash.github.io/rpc/getblockhash.html)
- [getblockhashes](https://zcash.github.io/rpc/getblockhashes.html)
- [getblockheader](https://zcash.github.io/rpc/getblockheader.html)
- [getchaintips](https://zcash.github.io/rpc/getchaintips.html)
- [getdifficulty](https://zcash.github.io/rpc/getdifficulty.html)
- [getmempoolinfo](https://zcash.github.io/rpc/getmempoolinfo.html)
- [getspentinfo](https://zcash.github.io/rpc/getspentinfo.html)
- [gettxout](https://zcash.github.io/rpc/gettxout.html)
- [gettxoutsetinfo](https://zcash.github.io/rpc/gettxoutsetinfo.html)
- [z_gettreestate](https://zcash.github.io/rpc/z_gettreestate.html)
- [getmininginfo](https://zcash.github.io/rpc/getmininginfo.html)
- [getnetworksolps](https://zcash.github.io/rpc/getnetworksolps.html)
- [getnetworkinfo](https://zcash.github.io/rpc/getnetworkinfo.html)
- [getpeerinfo](https://zcash.github.io/rpc/getpeerinfo.html)
- [ping](https://zcash.github.io/rpc/ping.html)

- Blocked on #110

**Comment by AloeareV** [comment]
`send_raw_transaction` needs to interface with the mempool, I think this puts it in the scope of #118 and not this issue? I think there are other mempool-related ones (`getrawmempool` I assume) but that's the first one I've hit.

**Comment by idky137** [comment]
Code added in #178, Tests will be added in https://github.com/zingolabs/zaino/issues/114

**Comment by pacu** [comment]
How are we standing on this particular issue? @AloeareV @idky137, could you mark the completed methods that are specified as tasks ?

**Comment by zancas** [comment]
> How are we standing on this particular issue? [@AloeareV](https://github.com/AloeareV) [@idky137](https://github.com/idky137), could you mark the completed methods that are specified as tasks ?

Yes please!

**Comment by pacu** [comment]
@AloeareV says this is done, would you do the honors of closing this one out?

**Comment by AloeareV** [comment]
Completed by #178
