### ISSUE TITLE
1.1 - Update Zaino-Testutils for ZIP317 and ZIP320

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#48]
Zaino's Zingolib and liobrustzcash dependencies need to be updated for ZIP317 and ZIP320 before integration with Zebra. There are also several other bugs that have been fixed in lightwalletd in the last few months that has caused changed in the expected behaviour by light wallets.

### Tasks
 - [x] Task 1: Temporarily remove Nym code to allow development on Zaino while the dependency conflict is being fixed.
 - [x] Task 2: Update dependency versions  and fix and error in Zaino-testutils from update.
 - [x] Task 3: Fix https://github.com/zcash/lightwalletd/issues/493 in Zaino.

- Blocked on https://github.com/zingolabs/zingolib/pull/1386.

**Comment by idky137** [comment]
Merging #74, #75, #76 and #77 will complete this deliverable.
