### ISSUE TITLE
1.2 - Explicitly mark and broadcast list of lightwallet gRPCs to be deprecated

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#49]
Communicate with Zcash community to finalise list of lightwallet RPCs to be deprecated and clearly mark in Zaino.

### Tasks:
- [x] Task 1: Communicate with lightwallet developers to find subset of services currently in use (#70).
- [x] Task 2: Communicate with ZF / ECC regarding the servicing of transparent data and decide plan for get_taddres_txids service (#71).
- [x] Task 3: Explicitly mark deprecated RPC's in Zaino.
- [x] Task 4: Produce full spec of lightwallet RPCs to be supported in Zaino. (This could be put forward in a ZIP now or this could wait until the extended wallet services have been decided in #57.)

**Comment by idky137** [comment]
Tasks 3 and 4 have been completed in #104. The spec will be finalised in #57
