### ISSUE TITLE
1.3 Convert Indexer service to use zebra’s primitives.

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#50]
Currently Zaino uses zcash primitives defined in Zaino-Fetch. Zaino-Serve should use Zebra's primitives directly to ease integration with Zebra's ReadStateService. For this either Zaino-Fetch should be converted to use Zebra's primitives directly or conversion impls should be implemented.

- Blocked on #48

### Tasks
- [ ] Task 1: *[Work in Zebra] Expose primitives as pub or provide getters / setters and derive Serde::deserialize.
- [ ] Task 2: Convert Zaino-Fetch to use Zebra's primitives directly or provide conversion impls.
- [ ] Task 3: Convert Zaino-Serve to use Zebra's primitives.

**Comment by idky137** [comment]
Merging #82 and https://github.com/ZcashFoundation/zebra/pull/8964 will complete this deliverable.
