### ISSUE TITLE
1.4 Implement test framework showing equivalence between legacy and new implementation.

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#51]
We need a test framework that creates a test chain using regtest mode then launches either lwd or Zaino and queries the server with a set of RPC requests that comprehensively test the functionality of the lightwallet service.

- Blocked on https://github.com/zingolabs/zingolib/pull/1386, #48

### Tasks
 - [x] Task 1: *[Work in Zingolib] Update Zingo-Testutils to make both Lightwalletd and Zcashd optional, Zaino (and possibly Zebra) should be added as new options for test indexer (and validator).
 - [x] Task 2: Create test chain using regtest mode that can be loaded and queried for RPC tests.
 - [x] Task 3: Create set of tests that comprehensively test the functionality of the lightwallet gRPC services in both Lightwalletd and Zaino.

**Comment by idky137** [comment]
The majority of this work is being completed in https://github.com/zingolabs/zcash-local-net

**Comment by idky137** [comment]
As Zebra is not required for comparing the functionality between Lightwalletd and Zaino, this functionality will be added during Milestone 2.

**Comment by idky137** [comment]
- Merging / Completing https://github.com/zingolabs/zaino/pull/88, https://github.com/zingolabs/zcash-local-net/pull/16, https://github.com/zingolabs/zcash-local-net/pull/18 and https://github.com/zingolabs/zcash-local-net/issues/17 will complete this deliverable.
