### ISSUE TITLE
2.1 - Implement Zcash RPC functionality required by lightwallet services, backed by Zebra's ReadStateService

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#54]
Integrate with Zebra's `ReadStateService` to access the finalised and non-finalised chain. This should be implemented in Zaino-State to be accessible as a standalone library.

Integration with `TrustedChainSync` for accessing the non-finalised state should be encapsulated, requiring no user-side setup.

Implement RPC functionality required by lightwallet RPC services backed by Zebra's `ReadStateService`, keeping backwards compatibility options where possible.

 - Blocked on:
       #50 
       #51
 - Task 2.1.5 Blocked on:
       #96

### Tasks
 - [x] [Task 2.1.1: Create StateService struct in Zaino-State, initially containing Zebra's ReadStateService, and implement sync method (using Zebra's TrustedChainSync) as a persistent background process.](https://github.com/zingolabs/zaino/issues/110)
 - [x] [Task 2.1.2: Implement Zcash RPC functionality required by lightwallet services.](https://github.com/zingolabs/zaino/issues/111)
 - [x] [Task 2.1.3: Add Indexer Trait.](https://github.com/zingolabs/zaino/issues/112)
 - [x] [Task 2.1.4: Implement Indexer for `StateService`](https://github.com/zingolabs/zaino/issues/113)
 - [x] [Task 2.1.5: Add tests for Zcash RPC functionality backed by  `StateService`.](https://github.com/zingolabs/zaino/issues/114)

**Comment by zancas** [comment]
Should 2.1.4 be marked as complete on this issue?
