### ISSUE TITLE
2.3 - Provide efficient Compact Block fetch and access to a local non-finalised state for backup RPC backend.

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#55]
Zaino currently fetches full blocks and parses them to compact blocks every time a client requests block data. This is very inefficient and access to a local compact block cache or at the very lease an internal non-finalised state is required for scale use. This will be inherited from Zebra when Zaino is backed by the `ReadStateService` (`StateService`) but this will still not be the case when Zaino uses its backup RPC backend (`FetchService`), with zcashd or other future RPC based validators. For this reason we need to implement an internal non-finalised state for `FetchService`.

- Task 2.3.1 partially Blocked on #116
- Task 2.3.4 Blocked on #96

### Tasks
 - [x] [Task 2.3.1: Create `FetchService` struct in `Zaino-State`, initially containing `Zaino-Fetch`'s JsonRpcConnector and a `non_finalised_state` struct, and implement sync method as a persistent background process.](https://github.com/zingolabs/zaino/issues/122)
 - [x] [Task 2.3.2: Implement `Indexer` for `FetchService`.](https://github.com/zingolabs/zaino/issues/123)
 - [x] [Task 2.3.3: Add `get_compact_block` method to `Indexer` trait and implement for `StateService` and `FetchService`.](https://github.com/zingolabs/zaino/issues/124)
 - [x] [Task 2.3.4: Add RPC test for get_compact_block and add RPC tests for `FetchService`](https://github.com/zingolabs/zaino/issues/125)

NOTE: If compact blocks are not available in the ReadStateService at the time this work is being implemented, `StateService` will continue parse data internally until the required indexes are available.
