### ISSUE TITLE
2.5 - Leverage implementation to contextualise and finalise full architecture of Zaino

### ISSUE THREAD

**Issue by idky137** [zingolabs/zingo-proxy#57]
Finalise design and spec of the remote wallet service (RemoteReadStateService / Extended "cli-wallet" gRPC Service). Provide full spec for consumers (wallets / block explorers) of both the public methods provided in the Zaino-state lib (for local chain access), and the remote services provided by the Zaino server.

- Blocked on #53, https://github.com/zcash/wallet/issues/7 

### Tasks
 - [x] [Task 2.5.1: Enumerate the set of indices required by full node wallets and block explorers.](https://github.com/zingolabs/zaino/issues/72)
 - [x] [Task 2.5.2: Agree on protocol spec for new RPC services.](https://github.com/zingolabs/zaino/issues/69).
 - [x] [Task 2.5.3: Finalise design documents and API specifications and add to Docs folder in Zaino.](https://github.com/zingolabs/zaino/issues/132)
