### ISSUE TITLE
2.2 Implement server optimisations necessary for wide scale testing and public use.

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingo-proxy#67]
Several server optimisations and specific error handling cases must be implemented for large-scale testing and live deployment.

### Tasks
 - [ ] [Task 2.2.1: Add error handling for specific errors to the `TcpIngestor`, `Worker` and `Director` in `Zaino-Serve`.](https://github.com/zingolabs/zaino/issues/126)
 - [ ] [Task 2.2.2: Add terminal log using ServerStatus struct in Zaino-Serve.](https://github.com/zingolabs/zaino/issues/127)
 - [ ] [Task 2.2.3: Add automatic server restart / shutdown for critical errors.](https://github.com/zingolabs/zaino/issues/128)
 - [ ] [Task 2.2.4: Add TLS Certification to gRPC server.](https://github.com/zingolabs/zaino/issues/129)
 - [ ] [Task 2.2.5: Refactor JsonRpcConnectorError and implement fmt::display.](https://github.com/zingolabs/zaino/issues/130)
 - [ ] [Task 2.2.5: Make Zaino and Zebra listen addresses fully configurable.](https://github.com/zingolabs/zaino/issues/131)

NOTE: This list of tasks is not exhaustive and should be updated as issues are found.
